# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'moise_alternatif_widgets.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 480)
        MainWindow.setToolTip("")
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Logo_Label = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Logo_Label.sizePolicy().hasHeightForWidth())
        self.Logo_Label.setSizePolicy(sizePolicy)
        self.Logo_Label.setMinimumSize(QtCore.QSize(200, 150))
        self.Logo_Label.setObjectName("Logo_Label")
        self.gridLayout_2.addWidget(self.Logo_Label, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.tableView = QtWidgets.QTableView(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tableView.setFont(font)
        self.tableView.setObjectName("tableView")
        self.gridLayout_2.addWidget(self.tableView, 1, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_add = QtWidgets.QPushButton(self.tab)
        self.pushButton_add.setObjectName("pushButton_add")
        self.horizontalLayout.addWidget(self.pushButton_add)
        self.pushButton_update = QtWidgets.QPushButton(self.tab)
        self.pushButton_update.setObjectName("pushButton_update")
        self.horizontalLayout.addWidget(self.pushButton_update)
        self.pushButton_remove = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_remove.sizePolicy().hasHeightForWidth())
        self.pushButton_remove.setSizePolicy(sizePolicy)
        self.pushButton_remove.setObjectName("pushButton_remove")
        self.horizontalLayout.addWidget(self.pushButton_remove)
        self.pushButton_send_mail = QtWidgets.QPushButton(self.tab)
        self.pushButton_send_mail.setObjectName("pushButton_send_mail")
        self.horizontalLayout.addWidget(self.pushButton_send_mail)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_type_msn = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_type_msn.setObjectName("comboBox_type_msn")
        self.gridLayout.addWidget(self.comboBox_type_msn, 0, 0, 1, 1)
        self.comboBox_ss_type_msn = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_ss_type_msn.setObjectName("comboBox_ss_type_msn")
        self.gridLayout.addWidget(self.comboBox_ss_type_msn, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 5, 0, 1, 1)
        self.lineEdit_commentaires = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_commentaires.setText("")
        self.lineEdit_commentaires.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_commentaires.setObjectName("lineEdit_commentaires")
        self.gridLayout_4.addWidget(self.lineEdit_commentaires, 6, 0, 1, 1)
        self.comboBox_pilot2 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_pilot2.setObjectName("comboBox_pilot2")
        self.gridLayout_4.addWidget(self.comboBox_pilot2, 1, 0, 1, 1)
        self.pushButton_snapshot_template = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_snapshot_template.setObjectName("pushButton_snapshot_template")
        self.gridLayout_4.addWidget(self.pushButton_snapshot_template, 9, 0, 1, 1)
        self.pushButton_aircraft = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_aircraft.setObjectName("pushButton_aircraft")
        self.gridLayout_4.addWidget(self.pushButton_aircraft, 12, 0, 1, 1)
        self.pushButton_termplate_create = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_termplate_create.setObjectName("pushButton_termplate_create")
        self.gridLayout_4.addWidget(self.pushButton_termplate_create, 10, 0, 1, 1)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox_2)
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit.setTimeSpec(QtCore.Qt.UTC)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout_4.addWidget(self.dateTimeEdit, 3, 0, 1, 1)
        self.pushButton_add_pilot = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_add_pilot.setWhatsThis("")
        self.pushButton_add_pilot.setObjectName("pushButton_add_pilot")
        self.gridLayout_4.addWidget(self.pushButton_add_pilot, 11, 0, 1, 1)
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.groupBox_2)
        self.dateTimeEdit_2.setCalendarPopup(True)
        self.dateTimeEdit_2.setTimeSpec(QtCore.Qt.UTC)
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.gridLayout_4.addWidget(self.dateTimeEdit_2, 4, 0, 1, 1)
        self.comboBox_pilot1 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_pilot1.setObjectName("comboBox_pilot1")
        self.gridLayout_4.addWidget(self.comboBox_pilot1, 0, 0, 1, 1)
        self.comboBox_aircraft = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_aircraft.setObjectName("comboBox_aircraft")
        self.gridLayout_4.addWidget(self.comboBox_aircraft, 2, 0, 1, 1)
        self.rmv_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.rmv_btn.setObjectName("rmv_btn")
        self.gridLayout_4.addWidget(self.rmv_btn, 13, 0, 1, 1)
        self.pushButton_insert = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_insert.setAutoDefault(False)
        self.pushButton_insert.setDefault(True)
        self.pushButton_insert.setObjectName("pushButton_insert")
        self.gridLayout_4.addWidget(self.pushButton_insert, 7, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 0, 3, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_search = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_search.setClearButtonEnabled(True)
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.horizontalLayout_2.addWidget(self.lineEdit_search)
        self.checkBox_pcb = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_pcb.setObjectName("checkBox_pcb")
        self.horizontalLayout_2.addWidget(self.checkBox_pcb)
        self.checkBox_pcm = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_pcm.setObjectName("checkBox_pcm")
        self.horizontalLayout_2.addWidget(self.checkBox_pcm)
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit.sizePolicy().hasHeightForWidth())
        self.dateEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.dateEdit.setFont(font)
        self.dateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_2.addWidget(self.dateEdit)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_2.sizePolicy().hasHeightForWidth())
        self.dateEdit_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.dateEdit_2.setFont(font)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.horizontalLayout_2.addWidget(self.dateEdit_2)
        self.lineEdit_search_mission = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_search_mission.setClearButtonEnabled(True)
        self.lineEdit_search_mission.setObjectName("lineEdit_search_mission")
        self.horizontalLayout_2.addWidget(self.lineEdit_search_mission)
        self.gridLayout_3.addWidget(self.groupBox, 0, 1, 1, 3)
        self.tableView_2 = QtWidgets.QTableView(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableView_2.setFont(font)
        self.tableView_2.setObjectName("tableView_2")
        self.gridLayout_3.addWidget(self.tableView_2, 1, 1, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setStyleSheet("border-color: rgb(179, 179, 179); border-top-color:\n"
                                   "                                                rgb(252, 2, 128);\n"
                                   "                                                font: 75 10pt \"MS Shell Dlg 2\";\n"
                                   "                                            ")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 1, 1, 1)
        self.comboBox_price_aircraft = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_price_aircraft.setObjectName("comboBox_price_aircraft")
        self.gridLayout_3.addWidget(self.comboBox_price_aircraft, 2, 2, 1, 1)
        self.label_price = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_price.setFont(font)
        self.label_price.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_price.setAlignment(QtCore.Qt.AlignCenter)
        self.label_price.setObjectName("label_price")
        self.gridLayout_3.addWidget(self.label_price, 2, 3, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_5.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 950, 18))
        self.menubar.setObjectName("menubar")
        self.menuMENU = QtWidgets.QMenu(self.menubar)
        self.menuMENU.setObjectName("menuMENU")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_save_file = QtWidgets.QAction(MainWindow)
        self.action_save_file.setObjectName("action_save_file")
        self.menuMENU.addAction(self.action_save_file)
        self.menubar.addAction(self.menuMENU.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.comboBox_pilot1, self.comboBox_pilot2)
        MainWindow.setTabOrder(self.comboBox_pilot2, self.comboBox_aircraft)
        MainWindow.setTabOrder(self.comboBox_aircraft, self.dateTimeEdit)
        MainWindow.setTabOrder(self.dateTimeEdit, self.dateTimeEdit_2)
        MainWindow.setTabOrder(self.dateTimeEdit_2, self.rmv_btn)
        MainWindow.setTabOrder(self.rmv_btn, self.dateEdit_2)
        MainWindow.setTabOrder(self.dateEdit_2, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.tableView)
        MainWindow.setTabOrder(self.tableView, self.pushButton_remove)
        MainWindow.setTabOrder(self.pushButton_remove, self.pushButton_send_mail)
        MainWindow.setTabOrder(self.pushButton_send_mail, self.pushButton_add)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Logo_Label.setText(
            _translate("MainWindow", "<html><head/><body><p><img src=\":/mes_logos/logo_tres_petit.jpg\"width=\"180\"\n"
                                     "                                                height=\"100\"/></p></body></html>\n"
                                     "                                            "))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span\n"
                                                    "                                                style=\" color:#800002;\">MOISE : Moyen Operationnel\n"
                                                    "                                                d\'Information et de\n"
                                                    "                                                Soutien des Equipages </span></p></body></html>\n"
                                                    "                                            "))
        self.pushButton_add.setText(_translate("MainWindow", "INSERER"))
        self.pushButton_update.setText(_translate("MainWindow", "MAJ JOURS"))
        self.pushButton_remove.setText(_translate("MainWindow", "SUPPRIMER"))
        self.pushButton_send_mail.setText(_translate("MainWindow", "ENVOYER"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "LIMITES"))
        self.groupBox_2.setTitle(_translate("MainWindow", "INSERTION"))
        self.groupBox_3.setTitle(_translate("MainWindow", "MISSIONS"))
        self.lineEdit_commentaires.setPlaceholderText(_translate("MainWindow", "Commentaire"))
        self.pushButton_snapshot_template.setText(_translate("MainWindow", "SNAPSHOT TEMPLATE"))
        self.pushButton_aircraft.setText(_translate("MainWindow", "AIRCRAFT"))
        self.pushButton_termplate_create.setText(_translate("MainWindow", "CREER TEMPLATE "))
        self.dateTimeEdit.setDisplayFormat(_translate("MainWindow", "yyyy/MM/dd HH:mm"))
        self.pushButton_add_pilot.setText(_translate("MainWindow", "PILOT"))
        self.dateTimeEdit_2.setDisplayFormat(_translate("MainWindow", "yyyy/MM/dd HH:mm"))
        self.rmv_btn.setText(_translate("MainWindow", "REMOVE"))
        self.pushButton_insert.setText(_translate("MainWindow", "INSERT"))
        self.groupBox.setTitle(_translate("MainWindow", "FILTRE"))
        self.lineEdit_search.setPlaceholderText(_translate("MainWindow", "recherche pilote/appareil"))
        self.checkBox_pcb.setText(_translate("MainWindow", "PCB"))
        self.checkBox_pcm.setText(_translate("MainWindow", "PCM"))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "yyyy/MM/dd"))
        self.dateEdit_2.setDisplayFormat(_translate("MainWindow", "yyyy/MM/dd"))
        self.lineEdit_search_mission.setPlaceholderText(_translate("MainWindow", "recherche mission"))
        self.label_2.setToolTip(_translate("MainWindow", "update me"))
        self.label_2.setText(_translate("MainWindow", "MAJ VIA UPDATE"))
        self.label_price.setText(_translate("MainWindow", "PRIX"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "LOG"))
        self.menuMENU.setTitle(_translate("MainWindow", "MENU"))
        self.action_save_file.setText(_translate("MainWindow", "SAUVEGARDER BASE DE DONEE"))

